# RandomTeleport by PixelArray [BETA]
# Players are teleported relative to their current position.

# DO NOT CHANGE THIS
version: "{$project.version}"

# Cooldown (in seconds)
cooldown_timer: 300

# The teleport distance is a random value between minimum_range and maximum_range.
# Default: The player's X and Z coordinates with be changed 25 to 600 blocks away from their original coordinate.
minimum_range: 25
maximum_range: 600