# RandomTeleport by PixelArray [BETA]
# Players are teleported relative to their current position.

# The chat prefix for all RTP messages
prefix_msg: "&8[&cRTP&8] "
# The message the player is sent upon teleportation. METERS will be replaced by distance teleported in meters (1 meter = 1 block).
notification_msg: "&7You've been teleported METERS blocks away!"
# The message the player is sent if they're on cooldown. SECONDS will be replaced by seconds left on cooldown.
cooldown_msg: "&7You must wait SECONDS seconds to teleport again."

# Cooldown (in seconds)
cooldown_timer: 300

# The teleport distance is a random value between minimum_range and maximum_range.
# Default: The player's X and Z coordinates with be changed 25 blocks all the way up to 600 blocks from the original coordinate.

# Pythagorean Theorem can be used to find the minimum and maximum distance the player will be teleported.
# Default: The player will be teleported minimum ~35.5 blocks away and maximum ~848.5 blocks away (On a 2D coordinate plane)
minimum_range: 25
maximum_range: 600