name: RandomTeleport
version: ${project.version}
main: me.kyleseven.randomteleport.RandomTeleport
api-version: 1.13
authors: [kyleseven]
description: Allows players to teleport to a random location within the world.